### PR TITLE
fix(log): register the server error filter in web.xml, not in the director

### PR DESCRIPTION
**Pull request by marevol**
Stacked on #3383. Fixes the `build` job failure that every PR from #3371 onward inherits.

## What fails

`CrawlerLogTests` and `FailureUrlTests` fail in the `Run Integration Test` step:

```
CrawlerLogTests.crawlingInfoTest:133->testReadCrawlingInfo:221 expected: <1> but was: <0>
CrawlerLogTests.failureUrlTest:148->testReadFailureUrl:286 expected: <1> but was: <0>
CrawlerLogTests.searchListTest:156->testReadSearchList:305 expected: <true> but was: <false>
FailureUrlTests.crudTest:104->testReadFailureUrlLogs:130 Should have at least one failure URL log
```

The tests are reporting a symptom: no crawl runs at all. The server log in the same
step shows every child process dying at DI container startup:

```
JobProcessingException: Exit Code: 1
DiXmlParseFailureException: lastaflute_director.xml included by lastaflute_assist.xml
Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/Filter
```

## Why

`ServerErrorLoggingFilter` (#3371) was registered through
`FwWebDirection#directServletFilter` in `FessFwAssistantDirector`. That class is the one
`lastaflute_director.xml` names, and `lastaflute_assist.xml` includes that file into the
container the crawler, thumbnail, suggest and chunk child processes build for themselves.

Those processes run with `WEB-INF/classes` + `WEB-INF/lib` + `WEB-INF/env/<type>/lib` on
the classpath and no servlet API — Tomcat hands that to the webapp from the server's own
`lib` directory. Verifying the director loads the filter class, whose superinterface
`jakarta.servlet.Filter` is missing there, so the container fails to build and the job
exits 1. The webapp itself is unaffected, which is why nothing else in the build noticed.

Not caused by #3383, or by anything else in the stack: the same four failures appear on
every run from #3371 (`pr/06-log-server-error`) onward, including the docs-only #3381,
while #3370 is green.

## Fix

- Declare the filter in `web.xml`, mapped just ahead of `lastaShowbaseFilter`, so it still
  installs the per-thread server error handler outside `RequestLoggingFilter`.
- Drop the `directServletFilter` call, the factory method and the import from
  `FessFwAssistantDirector`, so no servlet type is reachable from it again.

## Tests

- `FessFwAssistantDirectorTest` loads every component `lastaflute_director.xml` names
  through a class loader that refuses `jakarta.servlet.*` the way a child process'
  classpath refuses it. Reverting the main-code change makes it fail with the same
  `NoClassDefFoundError: jakarta/servlet/Filter` the CI log shows.
- `ServerErrorLoggingFilterTest.test_registeredOutsideTheLoggingFilter` is replaced by
  `test_mappedAheadOfTheLoggingFilter`, which asserts the `web.xml` declaration and that
  the mapping precedes `lastaShowbaseFilter`. The three behavioural tests are unchanged.
- Verified separately that `FessFwAssistantDirector` now loads on a classpath without
  `jakarta.servlet.Filter` (the child-process classpath) and failed to before.
- `mvn test -Dtest='org.codelibs.fess.filter.*Test,org.codelibs.fess.webapp.*Test,org.codelibs.fess.mylasta.direction.*Test'`: 240 tests, 0 failures.

### CODE REVIEW

File: src/test/java/org/codelibs/fess/filter/ServerErrorLoggingFilterTest.java [hunk 1]
```diff
@@ -90,21 +101,59 @@ public void test_noServerError_logsNothing() throws Exception {
...
+    /** Returns the {@code filter-class} declared for the given {@code filter-name}, or null. */
+    private String filterClassOf(final Document webXml, final String filterName) {
+        final NodeList filters = webXml.getElementsByTagName("filter");
+        for (int i = 0; i < filters.getLength(); i++) {
+            final Element filter = (Element) filters.item(i);
+            if (filterName.equals(textOf(filter, "filter-name"))) {
+                return textOf(filter, "filter-class");
+            }
         }
+        return null;
```
Comment (utafrali) [inline src/test/java/org/codelibs/fess/filter/ServerErrorLoggingFilterTest.java:143]: `parseWebXml()` creates a `DocumentBuilderFactory` without disabling external DTD loading, unlike the parallel `readComponentClassNames()` in `FessFwAssistantDirectorTest` which sets `load-external-dtd` to `false`. This `web.xml` uses schema-based validation and has no `DOCTYPE`, so it won't trigger a network call in practice. But the inconsistency is a small trap for future readers, and in environments that block outbound DNS it could flake if the file ever gains a DOCTYPE. Apply the same guard:

```java
final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
return factory.newDocumentBuilder().parse(file);
```

File: src/test/java/org/codelibs/fess/mylasta/direction/FessFwAssistantDirectorTest.java [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+        ServletFreeClassLoader(final ClassLoader parent) {
+            super(parent);
+        }
+
+        @Override
+        protected Class<?> loadClass(final String name, final boolean resolve) throws ClassNotFoundException {
+            if (name.startsWith(MISSING_PACKAGE_PREFIX)) {
+                throw new ClassNotFoundException(name + " is not on a child process' classpath");
+            }
+            if (!name.startsWith(APPLICATION_PACKAGE_PREFIX)) {
```
Comment (utafrali) [inline src/test/java/org/codelibs/fess/mylasta/direction/FessFwAssistantDirectorTest.java:113]: `ServletFreeClassLoader` blocks `jakarta.servlet.*` only when the requesting class is under `org.codelibs.fess.*`. A `org.lastaflute.*` or `org.dbflute.*` class referenced from the director that itself references a servlet type would go through the parent loader (which does have the servlet API) and the test would not catch the regression. This is an acceptable scope given the specific bug pattern here, but a short comment on this limitation would help future readers understand what the test does and does not cover.

**Review by utafrali — APPROVED** [review]
The fix is correct and well-targeted: pulling `ServerErrorLoggingFilter` out of the director and into `web.xml` removes the only servlet type from the DI path that child processes initialize, which is exactly what broke crawl jobs. The ordering invariant is preserved and documented, and `FessFwAssistantDirectorTest` is a genuinely useful regression guard. Two minor points about the `parseWebXml` DTD guard and the classloader scope are worth a look, but neither blocks merging.

File: src/test/java/org/codelibs/fess/filter/ServerErrorLoggingFilterTest.java (hunk 1 above)
Comment (marevol) [reply src/test/java/org/codelibs/fess/filter/ServerErrorLoggingFilterTest.java:143]: Applied. `parseWebXml()` now sets the same `load-external-dtd` guard, with a comment saying why it is there even though `web.xml` is schema-based and has no `DOCTYPE` today. Folded into the existing commit.

File: src/test/java/org/codelibs/fess/mylasta/direction/FessFwAssistantDirectorTest.java (hunk 2 above)
Comment (marevol) [reply src/test/java/org/codelibs/fess/mylasta/direction/FessFwAssistantDirectorTest.java:113]: Correct, and documented now. The class javadoc of `ServletFreeClassLoader` says that only the classes this loader defines see the refusal: anything outside `org.codelibs.fess.*` is defined by the parent loader and keeps resolving against the parent's classpath, which does have the servlet API. So it catches a servlet type reachable from Fess' own code -- where the components in `lastaflute_director.xml` live and where this regression happened -- but not one introduced through a framework class. Folded into the existing commit.
